services:
  omni-database:
    image: postgres:16-alpine
    container_name: omni-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: omni_switch_db
    ports:
      - "5432:5432"
    volumes:
      - omni-database-data:/var/lib/postgresql/data
volumes:
  omni-database-data: